# .github/workflows/getSubscriptionDetails.yaml

name: Get Subscription Details

on:
  workflow_call:
    inputs:
      EnvironmentType:
        required: true
        type: string
      Subscription:
        required: true
        type: string

jobs:
  get_subscription_details:
    runs-on: ubuntu-latest
    outputs:
      subscription: ${{ steps.get_subscription_details.outputs.subscription }}
      storage_acc_name: ${{ steps.get_subscription_details.outputs.stoarge_acc_name }}
      subscription_id: ${{ steps.get_subscription_details.outputs.subscription_id }}
      aad_owner_obj_id: ${{ steps.get_subscription_details.outputs.aad_owner_obj_id }}
      aad_contributor_obj_id: ${{ steps.get_subscription_details.outputs.aad_contributor_obj_id }}
    steps:
      - name: Set up subscription and storage details
        id: get_subscription_details
        run: |
          env_type="${{ inputs.EnvironmentType }}"
          subscription="${{ inputs.Subscription }}"

          # Define the mappings
          declare -A subscriptionMap=(
            ["test"]="nlpaas-nonprod"
            ["dev"]="arkaas-nonprod"
            ["qa"]="arkaas-nonprod"
            ["perf"]="arkaas-prod"
            ["stage"]="nlpaas-prod"
            ["prod"]="nlpaas-prod"
            ["dev1"]="nlpaas-nonprod"
            ["qa1"]="nlpaas-nonprod"
            ["perf1"]="arkaas-prod"
            ["stage1"]="nlpaas-prod"
            ["prod1"]="nlpaas-prod"
            ["ark"]="arkaas-prod"
          )

          declare -A stoargeAccMap=(
            ["nlpaas-nonprod"]="enlptfstatenlpaasnp"
            ["arkaas-nonprod"]="enlptfstatearkaasnp"
            ["nlpaas-prod"]="enlptfstatenlpaas"
            ["arkaas-prod"]="enlptfstatearkaas"
          )

          declare -A subscriptionIdMap=(
            ["nlpaas-nonprod"]="c13d3595-ec03-436d-b30a-b21c2b16d804"
            ["arkaas-nonprod"]="a95b54af-d65e-43db-a558-7e116c319431"
            ["nlpaas-prod"]="35518787-d32f-4d45-b675-8bd976a6e850"
            ["arkaas-prod"]="e324c324-96f1-4d57-b7b1-8acaabc5ef87"
          )

          declare -A aadOwnerGroupObjectIdMap=(
            ["nlpaas-nonprod"]="ef9a44b0-f87a-4442-b6f5-43cca12c3251"
            ["arkaas-nonprod"]="40b1f146-6afb-4c6b-8605-e6906048725b"
            ["nlpaas-prod"]="ea39ef9d-1ad4-4ae4-a438-d5a18a4375c3"
            ["arkaas-prod"]="c110fd06-c0c6-4767-96aa-3c5f9813483a"
          )

          declare -A aadContributorGroupObjectIdMap=(
            ["nlpaas-nonprod"]="6b0d03a0-6d4c-405a-afce-aab508d0d049"
            ["arkaas-nonprod"]="472ea02d-a12d-4e08-9ae2-ea79407b77bd"
            ["nlpaas-prod"]="2e3a62f9-ad10-4647-9a55-77f9ac8211f1"
            ["arkaas-prod"]="cfd34da3-75be-47fc-a025-98a79bd6d399"
          )

          if [[ "$env_type" == "null" && "$subscription" != "null" ]]; then
            echo "subscription_id=${subscriptionIdMap[$subscription]}" >> $GITHUB_ENV
            echo "stoarge_acc_name=${stoargeAccMap[$subscription]}" >> $GITHUB_ENV
            echo "aad_owner_obj_id=${aadOwnerGroupObjectIdMap[$subscription]}" >> $GITHUB_ENV
            echo "aad_contributor_obj_id=${aadContributorGroupObjectIdMap[$subscription]}" >> $GITHUB_ENV
          else
            resolved_subscription="${subscriptionMap[$env_type]}"
            echo "subscription=$resolved_subscription" >> $GITHUB_ENV
            echo "stoarge_acc_name=${stoargeAccMap[$resolved_subscription]}" >> $GITHUB_ENV
            echo "subscription_id=${subscriptionIdMap[$resolved_subscription]}" >> $GITHUB_ENV
            echo "aad_owner_obj_id=${aadOwnerGroupObjectIdMap[$resolved_subscription]}" >> $GITHUB_ENV
            echo "aad_contributor_obj_id=${aadContributorGroupObjectIdMap[$resolved_subscription]}" >> $GITHUB_ENV
          fi
